Repository AlexandreTO/Projet, pull requests merged in 2021-09, with the labels that each got.

#49 Projet workflow
  .github/workflows/php.yml
  Readme.md
  composer.json
  composer.lock
  public/index.php
  src/Controller/CartController.php
  symfony.lock
  templates/cart/cart.html.twig
Labels: Tests

#54 Assert affichage
  Readme.md
  package-lock.json
  src/Controller/UserController.php
  src/Entity/User.php
  src/Form/AddUserType.php
  templates/user/addUser.html.twig
Labels: Fix

#60 Fixs
  .env
  config/packages/security.yaml
  templates/backOffice/base.html.twig
  templates/base.html.twig
Labels: Fix

#63 Fixs mineurs et design
  assets/js/components/back/Products.js
  assets/js/components/back/ProductsView.js
  assets/js/components/back/Users.js
  assets/js/components/front/Categories.js
  assets/js/components/front/Products.js
  assets/js/components/front/ProductsView.js
  assets/js/components/front/UserCommands.js
  config/packages/security.yaml
  src/Controller/BackControllers/BackCategoriesController.php
  src/Controller/CartController.php
  src/Form/CategoryType.php
  src/Form/ProductFormType.php
  templates/backOffice/base.html.twig
  templates/backOffice/categories/index.html.twig
  templates/backOffice/commands/_delete_form.html.twig
  templates/backOffice/commands/edit.html.twig
  templates/backOffice/commands/index.html.twig
  templates/backOffice/commands/show.html.twig
  templates/backOffice/products/addProducts.html.twig
  templates/backOffice/products/updateProduct.html.twig
  templates/backOffice/users/addUser.html.twig
  templates/backOffice/users/updateUser.html.twig
  templates/backOffice/users/users.html.twig
  templates/base.html.twig
  templates/cart/cart.html.twig
  templates/commande/show.html.twig
  templates/navbar.html.twig
  templates/payment/cancel.html.twig
  templates/payment/success.html.twig
  templates/products/viewProduct.html.twig
  templates/security/login.html.twig
  templates/user/addUser.html.twig
  templates/user/commands.html.twig
Labels: enhancement, Fix

#64 Empecher ajout
  src/Controller/CartController.php
Labels: enhancement, Fix
